spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradingmk
    username: davorangelov
    password: 12345
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/ddl.sql
      data-locations: classpath:sql/dml.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: tradingmkalerts@gmail.com
    password: YOUR_APP_PASSWORD
    protocol: smtp
    tls: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
